import{a as g,S as f,i}from"./assets/vendor-ClnZnm6g.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const y="45248332-5310999e5b0f9864a5c1f02e8",v="https://pixabay.com/api/";async function m(a,t,o){const n={key:y,q:a,image_type:"photo",orientation:"horizontal",page:t,per_page:20,safesearch:!0};try{return(await g.get(v,{params:n})).data}catch(e){iziToast.error({position:"topRight",message:`${e}`})}}const u={list:document.querySelector(".gallery")},L=new f(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function p(a){const t=a.hits.map(o=>`<div class="image-size">
            <a href="${o.largeImageURL}">
              <img class="image" src="${o.webformatURL}" alt="${o.tags}" />
            </a>
            <div class ="text-wraper">
              <div class="text-block"><h5>likes</h5><p>${o.likes}</p></div>
              <div class="text-block"><h5>views</h5><p>${o.views}</p></div>
              <div class="text-block"><h5>comments</h5><p>${o.comments}</p></div>
              <div class="text-block"><h5>downloads</h5><p>${o.downloads}</p></div>
            </div>
        </div>`).join("");u.list.insertAdjacentHTML("beforeend",t),L.refresh()}function b(){u.list.innerHTML=""}function w(){const a=u.list.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}const s={form:document.querySelector(".form"),input:document.querySelector(".form-input"),loader:document.querySelector(".loader"),button:document.querySelector(".load-button"),message:document.querySelector(".bottom")},l=15;let c=1,h="";s.form.addEventListener("submit",S);s.button.addEventListener("click",x);async function S(a){a.preventDefault(),b();const t=s.input.value.trim();if(c=1,h=t,t===""){i.error({position:"topRight",message:"Please fill the input"});return}s.loader.classList.remove("hidden"),s.message.classList.remove("show-text");try{const o=await m(t,c,l);if(o.total===0){i.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),s.loader.classList.add("hidden");return}else await p(o),s.loader.classList.add("hidden"),s.button.classList.remove("hidden")}catch(o){i.error({position:"topRight",message:o.message}),s.loader.classList.add("hidden")}}async function x(a){c+=1,s.loader.classList.remove("hidden"),s.button.classList.add("hidden");try{const t=await m(h,c,l);t.hits.length<l?(s.button.classList.add("hidden"),s.message.classList.add("show-text"),i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})):s.button.classList.remove("hidden"),await p(t),w(),s.loader.classList.add("hidden")}catch(t){i.error({position:"topRight",message:t.message}),s.loader.classList.add("hidden")}}
//# sourceMappingURL=commonHelpers.js.map
