import{a as g,S as f,i}from"./assets/vendor-ClnZnm6g.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const y="45248332-5310999e5b0f9864a5c1f02e8",L="https://pixabay.com/api/";async function m(a,s,o){const n={key:y,q:a,image_type:"photo",orientation:"horizontal",page:s,per_page:20,safesearch:!0};try{return(await g.get(L,{params:n})).data}catch(t){iziToast.error({position:"topRight",message:`${t}`})}}const u={list:document.querySelector(".gallery")},v=new f(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function p(a){const s=a.hits.map(o=>`<div class="image-size">
            <a href="${o.largeImageURL}">
              <img class="image" src="${o.webformatURL}" alt="${o.tags}" />
            </a>
            <div class ="text-wraper">
              <div class="text-block"><h5>likes</h5><p>${o.likes}</p></div>
              <div class="text-block"><h5>views</h5><p>${o.views}</p></div>
              <div class="text-block"><h5>comments</h5><p>${o.comments}</p></div>
              <div class="text-block"><h5>downloads</h5><p>${o.downloads}</p></div>
            </div>
        </div>`).join("");u.list.insertAdjacentHTML("beforeend",s),v.refresh()}function b(){u.list.innerHTML=""}function w(){const a=u.list.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}const e={form:document.querySelector(".form"),input:document.querySelector(".form-input"),loader:document.querySelector(".loader"),button:document.querySelector(".load-button"),message:document.querySelector(".bottom")},c=15;let d=1,h="";e.form.addEventListener("submit",x);e.button.addEventListener("click",S);async function x(a){a.preventDefault(),b();const s=e.input.value.trim();if(d=1,h=s,s===""){i.error({position:"topRight",message:"Please fill the input"});return}e.loader.classList.remove("hidden"),e.message.classList.remove("show-text");try{const o=await m(s,d,c);if(o.total===0){i.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),e.loader.classList.add("hidden"),e.button.classList.add("hidden");return}else await p(o),e.loader.classList.add("hidden"),o.totalHits<=c?(e.button.classList.add("hidden"),e.message.classList.add("show-text")):e.button.classList.remove("hidden")}catch(o){i.error({position:"topRight",message:o.message}),e.loader.classList.add("hidden")}}async function S(a){d+=1,e.loader.classList.remove("hidden"),e.button.classList.add("hidden");try{const s=await m(h,d,c);s.hits.length<c?(e.button.classList.add("hidden"),e.message.classList.add("show-text"),i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})):e.button.classList.remove("hidden"),await p(s),w(),e.loader.classList.add("hidden")}catch(s){i.error({position:"topRight",message:s.message}),e.loader.classList.add("hidden")}}
//# sourceMappingURL=commonHelpers.js.map
